// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTh28Mgd5i-FKaf3dcWTzA3yTtppUgkU',
    appId: '1:1025072596175:web:1ba3f36a98f5ba850a63ba',
    messagingSenderId: '1025072596175',
    projectId: 'lesson-thunder-fall',
    authDomain: 'lesson-thunder-fall.firebaseapp.com',
    storageBucket: 'lesson-thunder-fall.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdbdlHUXoDNA3kqy6qeIQk4a86bLcL1iI',
    appId: '1:1025072596175:android:5657f3cfb7e0b14f0a63ba',
    messagingSenderId: '1025072596175',
    projectId: 'lesson-thunder-fall',
    storageBucket: 'lesson-thunder-fall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt6akJEj2tFbNN4roU2DugTx9hzoEsYAM',
    appId: '1:1025072596175:ios:8c88ea8fd711637a0a63ba',
    messagingSenderId: '1025072596175',
    projectId: 'lesson-thunder-fall',
    storageBucket: 'lesson-thunder-fall.appspot.com',
    iosBundleId: 'com.example.lessonDay27Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt6akJEj2tFbNN4roU2DugTx9hzoEsYAM',
    appId: '1:1025072596175:ios:23d9bd69e5e86af40a63ba',
    messagingSenderId: '1025072596175',
    projectId: 'lesson-thunder-fall',
    storageBucket: 'lesson-thunder-fall.appspot.com',
    iosBundleId: 'com.example.lessonDay27Flutter.RunnerTests',
  );
}
