// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSyeTrvUVniEevAGWPW1tQ941bQabTz0',
    appId: '1:953900295250:web:aca1451284078185086b8b',
    messagingSenderId: '953900295250',
    projectId: 'lesson-day-29-flutter',
    authDomain: 'lesson-day-29-flutter.firebaseapp.com',
    storageBucket: 'lesson-day-29-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuHQhTNEv_ZJe6wmePyerEjL_ynoPP_SE',
    appId: '1:953900295250:android:19fc7b78c4a571bf086b8b',
    messagingSenderId: '953900295250',
    projectId: 'lesson-day-29-flutter',
    storageBucket: 'lesson-day-29-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaEgxi1pvjmajUtBDoKIOkera9A0YVBGM',
    appId: '1:953900295250:ios:c1c948c619ad28b5086b8b',
    messagingSenderId: '953900295250',
    projectId: 'lesson-day-29-flutter',
    storageBucket: 'lesson-day-29-flutter.appspot.com',
    iosBundleId: 'com.example.lessonDay31Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaEgxi1pvjmajUtBDoKIOkera9A0YVBGM',
    appId: '1:953900295250:ios:569c23fa8363a297086b8b',
    messagingSenderId: '953900295250',
    projectId: 'lesson-day-29-flutter',
    storageBucket: 'lesson-day-29-flutter.appspot.com',
    iosBundleId: 'com.example.lessonDay31Flutter.RunnerTests',
  );
}
