// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_Let5kMGG49M3vrKWjWrn4Tq_mdB-E4',
    appId: '1:1093041536838:web:1d6b848a14ccc46196af47',
    messagingSenderId: '1093041536838',
    projectId: 'lesson-day-28-flutter',
    authDomain: 'lesson-day-28-flutter.firebaseapp.com',
    storageBucket: 'lesson-day-28-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmuvWgxxzP52VUFmhsiqYp24ZEoq8Iu00',
    appId: '1:1093041536838:android:a63a91bf1dffb1f196af47',
    messagingSenderId: '1093041536838',
    projectId: 'lesson-day-28-flutter',
    storageBucket: 'lesson-day-28-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoBJesE294fOe7-iGde2ZJsdHNbOmCJ_E',
    appId: '1:1093041536838:ios:3df0e2357753aa0b96af47',
    messagingSenderId: '1093041536838',
    projectId: 'lesson-day-28-flutter',
    storageBucket: 'lesson-day-28-flutter.appspot.com',
    iosBundleId: 'com.example.lessonDay28Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoBJesE294fOe7-iGde2ZJsdHNbOmCJ_E',
    appId: '1:1093041536838:ios:490fb860e6e7aedb96af47',
    messagingSenderId: '1093041536838',
    projectId: 'lesson-day-28-flutter',
    storageBucket: 'lesson-day-28-flutter.appspot.com',
    iosBundleId: 'com.example.lessonDay28Flutter.RunnerTests',
  );
}
